title: Nipun Shah # your name (or website title) here
logo: "/images/profiledp2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Eager Beaver
  <br>
  Responsible & Reliable
  <br>
  Dance Athirst
  <br>
  Ping Pong Enthusiastic  
  <br><br>
  <a href="https://in.linkedin.com/in/nipun-shah-666883159">View My LinkedIn Profile</a>
  <a href="https://www.canva.com/design/DAEEr1d6Np4/view">Resume</a>
theme: jekyll-theme-minimal
