title: Nipun Shah # your name (or website title) here
logo: "/images/profiledp2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Eager Beaver & Passionate Coder
  <br>
  Responsible & Reliable
  <br>
  I'm curious enough kindaa person, always esurient seeking knowledge. Apart from this I am dance athirst & also love to play table tennis 
  <br><br>
  <a href="https://in.linkedin.com/in/nipun-shah-666883159">![](/images/Linkedin.png)</a>
  <a href="https://www.canva.com/design/DAEEr1d6Np4/view">Resume</a>
theme: jekyll-theme-minimal
